[package]
name = "assorted-debian-utils"
version = "0.1.0"
edition = "2021"
authors = ["Sebastian Ramacher <sebastian@ramacher.at>"]

[dependencies]
serde = { version = "1.0", features = ["derive"]}
serde_yaml = "0.8"
