[package]
name = "assorted-debian-utils"
description = "Collection of various utilities for Debian work"
version = "0.2.0"
authors = ["Sebastian Ramacher <sebastian@ramacher.at>"]
repository = "https://github.com/sebastinas/drt-tools"
edition = "2021"
rust-version = "1.56"
license = "LGPL-3.0-or-later"
readme = "README.md"
keywords = ["debian"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
anyhow = "1.0"
rfc822-like = "0.2.1"
