[package]
name = "assorted-debian-utils"
description = "Collection of various utilities for Debian work"
version = "0.1.0"
authors = ["Sebastian Ramacher <sebastian@ramacher.at>"]
repository = "https://github.com/sebastinas/drt-tools"
edition = "2021"
rust-version = "1.56"
keywords = ["debian"]

[dependencies]
serde = { version = "1.0", features = ["derive"]}
serde_yaml = "0.8"
