[package]
name = "drt-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
debcontrol = "0.1"
debcontrol_struct = "0.3"
futures = "0.3"
futures-util = "0.3"
httpdate = "1.0"
indicatif = "0.15"
reqwest = { version = "0.11", features = ["stream"] }
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
tokio = { version = "1.13", features = ["full"] }
xdg = "2.4"
xz2 = "0.1"
