[package]
name = "drt-tools"
description = "Tools for Debian Release Team work"
version = "0.2.0"
authors = ["Sebastian Ramacher <sebastian@ramacher.at>"]
repository = "https://github.com/sebastinas/drt-tools"
license = "GPL-3.0-or-later"
edition = "2021"
rust-version = "1.56"
readme = "README.md"
keywords = ["debian"]

[workspace]
members = ["assorted-debian-utils"]

[dependencies]
assorted-debian-utils = { version = "0.2", path = "assorted-debian-utils" }
anyhow = "1.0"
futures = "0.3"
futures-util = "0.3"
httpdate = "1.0"
indicatif = "0.16"
regex = "1"
reqwest = { version = "0.11", features = ["stream"] }
rfc822-like = "0.2.1"
serde = { version = "1.0", features = ["derive"] }
structopt = { version = "0.3", default-features = false }
tokio = { version = "1.13", features = ["macros", "rt-multi-thread"] }
xdg = "2.4"
xz2 = "0.1"
